# Specifies the version of the Kubernetes API
apiVersion: v1
# The type of Kubernetes object (a Service)
kind: Service
metadata:
  # The name of our service
  name: wisecow-service
spec:
  # 'NodePort' exposes the service on a static port on each of the cluster's nodes.
  # This makes it very easy to access for local testing with Minikube or Kind.
  type: NodePort
  selector:
    # This is the crucial link: The service will forward traffic to any pod
    # that has the label 'app: wisecow'. Our deployment creates pods with this label.
    app: wisecow
  ports:
    # This section defines the port mapping
    - protocol: TCP
      # 'port' is the port on the service itself that will be exposed internally in the cluster
      port: 80
      # 'targetPort' is the port on the container that the service will send traffic to
      targetPort: 8080
